spring:
  application:
    name: akitect-cms
  datasource:
    url: jdbc:postgresql://localhost:5432/akitectcms
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: AkitectCmsHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          schema-generation:
            foreign-key-constraint-creation: AFTER_TABLE_CREATION
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

  security:
    user:
      name: admin
      password: admin
    basic:
      enabled: false
    remember-me:
      key: akitectCmsSecretKey
      token-validity-seconds: 2592000

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 3600
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
        secure: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never

logging:
  level:
    root: INFO
    io.akitect.cms: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/akitect-cms.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

akitect:
  cms:
    upload:
      dir: ${user.home}/akitect-cms/uploads
      allowed-content-types: image/jpeg,image/png,image/gif,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,video/mp4

    jwt:
      secret: =p2s5v8y/B?E(H+MbQeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(G+KbPeSgVkYp3s6v9y$B&E)H@McQfTjWmZq4t7w!z%C*F-JaNdRgUk
      expiration: 86400000

    pagination:
      default-page-size: 10
      max-page-size: 100

    url:
      frontend: http://localhost:8080
      admin: http://localhost:8080/admin


    redis:
      enabled: false
      host: localhost
      port: 6379
      password:


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full